#!/usr/bin/env bash
# modules/cloudflare.sh — Cloudflare real-IP nginx configuration

CF_CONF="/etc/nginx/conf.d/cloudflare-realip.conf"
CF_UPDATE_SCRIPT="/usr/local/sbin/lemp-cloudflare-update"
CF_SERVICE="cloudflare-ip-update"

module_install_cloudflare() {
    log_info "Installing Cloudflare real-IP module..."

    _cloudflare_write_update_script
    chmod +x "${CF_UPDATE_SCRIPT}"

    log_info "Fetching Cloudflare IP ranges..."
    "${CF_UPDATE_SCRIPT}"

    cat > "/etc/systemd/system/${CF_SERVICE}.service" <<EOF
[Unit]
Description=Update Cloudflare IP ranges for nginx real-IP
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=${CF_UPDATE_SCRIPT}
EOF

    cat > "/etc/systemd/system/${CF_SERVICE}.timer" <<EOF
[Unit]
Description=Weekly refresh of Cloudflare IP ranges

[Timer]
OnCalendar=weekly
Persistent=true

[Install]
WantedBy=timers.target
EOF

    systemctl daemon-reload
    systemctl enable --now "${CF_SERVICE}.timer"

    log_success "Cloudflare real-IP module installed."
}

module_remove_cloudflare() {
    log_info "Removing Cloudflare real-IP module..."

    systemctl disable --now "${CF_SERVICE}.timer" 2>/dev/null || true
    rm -f "/etc/systemd/system/${CF_SERVICE}.timer"
    rm -f "/etc/systemd/system/${CF_SERVICE}.service"
    systemctl daemon-reload

    rm -f "${CF_CONF}"
    rm -f "${CF_UPDATE_SCRIPT}"

    nginx -t && service_reload nginx 2>/dev/null || true
    log_success "Cloudflare real-IP module removed."
}

module_upgrade_cloudflare() {
    log_info "Refreshing Cloudflare IP ranges..."
    _cloudflare_write_update_script
    chmod +x "${CF_UPDATE_SCRIPT}"
    "${CF_UPDATE_SCRIPT}"
    log_success "Cloudflare IP ranges updated."
}

module_status_cloudflare() {
    print_header "Cloudflare real-IP"

    if [[ -f "${CF_CONF}" ]]; then
        status_line "Config" "${CF_CONF}" green
        local ip_count last_modified
        ip_count=$(grep -c "^set_real_ip_from" "${CF_CONF}" 2>/dev/null || echo 0)
        last_modified=$(stat -c '%y' "${CF_CONF}" 2>/dev/null | cut -d'.' -f1 || echo "unknown")
        status_line "IP ranges" "${ip_count}"
        status_line "Last updated" "${last_modified}"
    else
        status_line "Config" "not present" red
    fi

    local timer_state
    timer_state=$(service_status "${CF_SERVICE}.timer")
    if [[ "${timer_state}" == "active" ]]; then
        status_line "Update timer" "${timer_state} (weekly)" green
    else
        status_line "Update timer" "${timer_state}" red
    fi

    echo ""
}

# =============================================================================
# Internal helpers
# =============================================================================

_cloudflare_write_update_script() {
    cat > "${CF_UPDATE_SCRIPT}" <<'SCRIPT'
#!/usr/bin/env bash
# lemp-cloudflare-update — fetch Cloudflare IPs, write nginx conf, reload nginx
set -euo pipefail

# Load lemp-manager config for CLOUDFLARED_IP
LEMP_CONF="/opt/lemp-manager/lemp.conf"
CLOUDFLARED_IP=""
if [[ -f "${LEMP_CONF}" ]]; then
    source "${LEMP_CONF}"
fi

CF_CONF="/etc/nginx/conf.d/cloudflare-realip.conf"
CF_API="https://api.cloudflare.com/client/v4/ips"

tmp=$(mktemp)
trap 'rm -f "${tmp}"' EXIT

curl -sf --max-time 15 "${CF_API}" > "${tmp}" || {
    echo "ERROR: Failed to fetch Cloudflare IPs from ${CF_API}" >&2
    exit 1
}

python3 - "${CF_CONF}" "${tmp}" <<'PYEOF'
import sys, json, datetime

conf_path, json_path = sys.argv[1], sys.argv[2]

with open(json_path) as f:
    data = json.load(f)

result = data.get('result', {})
cidrs = result.get('ipv4_cidrs', []) + result.get('ipv6_cidrs', [])

if not cidrs:
    print("ERROR: No IP ranges returned from Cloudflare API", file=sys.stderr)
    sys.exit(1)

updated = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
lines = [
    '# Cloudflare real-IP ranges — auto-generated by lemp-manager',
    f'# Last updated: {updated}',
    '',
]
for cidr in cidrs:
    lines.append(f'set_real_ip_from {cidr};')

with open(conf_path, 'w') as f:
    f.write('\n'.join(lines) + '\n')

print(f'Written {len(cidrs)} IP ranges to {conf_path}')
PYEOF

if [[ -n "${CLOUDFLARED_IP:-}" ]]; then
    echo "set_real_ip_from ${CLOUDFLARED_IP}; # cloudflared container" >> "${CF_CONF}"
fi

printf '\nreal_ip_header CF-Connecting-IP;\nreal_ip_recursive on;\n' >> "${CF_CONF}"

nginx -t && systemctl reload nginx
SCRIPT
}
